### ISSUE TITLE
m88rs6060 - wrong ts speed when tuning higher order dvb-s2x modcodes

### ISSUE THREAD

**Issue by majortom9** [tbsdtv/linux_media#398]
On my TBS5930, I found a bug affecting dvb-s2x, and fixed it on my local tree.  Looking at the upstream source here
the same issue should occur in tbsdtv latest. I hope my description is enough for someone to address it here.

Noticed when tuning a dvb-s2x TP having SR 34285 16apsk FEC 25/36 that the Transport Stream
was only about 1/2 what it should be (only 50 some odd Mbps). After troubleshooting the issue led me to a bug in 
m88rs6060 module.  Because it's a DVB-S2X signal, in m88rs6060_set_clock_ratio() it was falling through the
 if block to DVB-S, which only has mod_fac of 2 (qpsk), thus why the speed was only 1/2 what it should have been.
Below clocks the TS at the right rate now, and the troublesome TP now plays perfectly.

```
diff --git a/drivers/media/dvb-frontends/m88rs6060.c b/drivers/media/dvb-frontends/m88rs6060.c
index a50cdefcb375..00034a060b76 100644
--- a/drivers/media/dvb-frontends/m88rs6060.c
+++ b/drivers/media/dvb-frontends/m88rs6060.c
@@ -2429,7 +2429,7 @@ static int m88rs6060_set_clock_ratio(struct m88rs6060_dev *dev )
 
        m88rs6060_get_channel_info(dev,&p_info);
 
-       if(p_info.type==MtFeType_DvbS2){
+       if(p_info.type==MtFeType_DvbS2 || p_info.type == MtFeType_DvbS2X){
                dev_dbg(&i2c->dev, "iPlsCode = 0x%02X\n", p_info.iPlsCode);
                switch(p_info.mod_mode)
                {
```

**Comment by crazycat69** [comment]
Fixed, thanks.
https://github.com/tbsdtv/linux_media/commit/bc9c6ba3b5c1638d8e505fd650091adccd14429c

**Comment by majortom9** [comment]
awesome, thx crazycat... 
sidenote, I was originally looking in to that after a report from a windows user with tbs5930 that they couldn't play that mux. Can't say is similar issue because I don't use windows at all. Just that there may be an issue with it in Windows.
Might be worth a look, if ur doing any windows development with 5930.

**Comment by crazycat69** [comment]
Yes, all drivers use common code from Montage Tech with this bug. But TBS PCI-E devices with this chip use auto TS clock, so this function not used.

**Comment by majortom9** [comment]
hmm, tbs5930 is a USB interface. Does that support the auto TS clock ur speaking of in windows?

**Comment by crazycat69** [comment]
need check it :) add **m88rs6060_config.ts_autoclock=1** to [tbs5930_frontend_attach()](https://github.com/tbsdtv/linux_media/blob/latest/drivers/media/usb/dvb-usb/tbs5930.c#L148C12-L148C35)

**Comment by crazycat69** [comment]
i just review original Montage tech code and windows driver sources - **mt_fe_dmd_rs6060_set_clock_ratio()** have some another code:

```
	mt_fe_dmd_rs6060_get_channel_info(handle, &p_info);

	if (handle->tp_cfg.mCurrentType == MtFeType_DvbS2)			// for dvb-s2
	{
		switch(p_info.mod_mode)

```

**mt_fe_dmd_rs6060_get_channel_info()** set **handle->tp_cfg.mCurrentType** _MtFeType_DvbS_ or _MtFeType_DvbS2_ - so this only linux driver issue.

**Comment by majortom9** [comment]
But what happens when MtFeType_Dvbs2x and not MtFeType_Dvbs2?
On this s2x TP, it will similarly fall thru that if block, won't it? Because it's not DVB-S2.
Wonder what the get_channel_info returns in windows when it's DVB-S2x?

**Comment by majortom9** [comment]
I had the windows user show me the data rate from their tbs5930 while tuned to that troublesome mux and it looks correct to me.
Same as what I get in linux, after the fix action. So their issue must be something else. Waiting on a .ts file to verify.
Not being familiar with the windows driver, I asked what version they had installed, and it's 'v1007_20240605'
Requested the user try the Win11 driver, 'tbs5930_release_v11007_20250509_win11.zip' see what happens.

**Comment by crazycat69** [comment]
Look like same driver compiled with MS VS2022, not work with Win7/8 anymore. WHQL-signed for Win10+ x64.

**Comment by majortom9** [comment]
Thanks Crazycat. If ya get a chance to have a look thru the windows code again.
Some more detail...

A different windows user, who just bought a new TBS5930 this week, recorded a Full TS File for me from Alt DVB today.
Had them tune 4120 V 32485 FEC 25/36. Same provider as the mux I was working with. And sent me the file.

TSReader Playing back the file says the stream full stream is ~ 70 Mbps. And each program is only 7 Mbps. The
files I capture in linux, which we fixed, shows 94.1 Mbps for the full stream, and ~ 10 Mbps for each program.
roughly what the DVB-S2x Calculator says it should be.

[url=https://ibb.co/wfmVxQ2][img]https://i.ibb.co/1kW1wX4/abc-99w-4120-v-34285-ts.png[/img][/url]

So, checking the DVB-S2x calculator, for theoretical bitrates, and looking for possible combinations that would result in such a low
bitrate (in the case of windows driver bug(s)). There are two possibilities I see right off the bat. Either one of these two
scenarios could result in an overall bitrate of 70 Mbps.

1.) Locks it fine, but some other function() thinks it's an 8psk signal, so it gets clocked in wrong, similar to what the linux module was doing originally.
[img]https://i.ibb.co/67L8cmvB/if-8psk-fec-25-36-instead-of-16apsk-fec-25-36.png[/img]

2.) Locks it fine, but some other function() thinks it's a 16apsk signal, but having the 8_15 FEC instead of the 25_36 FEC. Remembering the other bug we found in the linux module couple years ago, had exactly that problem. Locked 16apsk fec 25_36 fine, but reported it as fec 8_15. My initial suspicion is possibility 2.)

[img]https://i.ibb.co/Hf19wPgp/if-16apsk-fec-8-15-instead-of-fec25-36.png[/img]

**Comment by crazycat69** [comment]
So maybe this VCM transponder with 16APSK, 25/36 and 8PSK,8/15 frames ?

**Comment by majortom9** [comment]
No, other than being DVB-S2x 16apsk fec 25/36, is a regular full time Mux, CCM. Programs are clear using hevc. I think the data is being clocked wrong in windows, similar to what it was doing in linux originally. But via a different (possibly similar) bug in windows.
Do you remember this issue from linux? was couple years ago. where it was reporting 8_15 incorrectly when tuning an fec 25_36 mux like this one. wondering if there could be some similar confusion somewhere in the windows driver. 

https://github.com/tbsdtv/linux_media/issues/306

Is there some debug enabled driver I could tell em to install and run 'debugview' that would help to isolate further?

**Comment by crazycat69** [comment]
https://github.com/tbsdtv/linux_media/commit/d94513e97be429847a8bf6ba6bcf74492d3d24d9

Look like this not fixed in windows drivers, but fixed in my StreamReaderEx-BDA

**Comment by majortom9** [comment]
There ya go, so in windows if the similar function to linux m88rs6060_set_clock_ratio() that uses the parameters to help clock the data in properly, is being told fec 8_15 instead of fec 25_36 (TP is really 25_36) when calculating the clock it needs to pace the TS pkts properly, it would be way off, by the amount of difference between the fec 8_15, and fec 25_36 code rates, correct???

scenario 2.) dvb-s2x calculation above.

At the time that 8_15 / 25_36 bug was found, we didn't have anything we could actually view, and I never noticed the TS Speed being way wrong in linux. Fast forward two years, and we now have a couple ITC muxes to watch using that 
DVB-S2x 16apsk fec 25/36 so it only gets noticed now.

**Comment by crazycat69** [comment]
Self-signed debug builds windows drivers for [TBS 5930](https://sourceforge.net/projects/crazyscan/files/test/TBS5930-debug.rar) and [TBS 5530](https://sourceforge.net/projects/crazyscan/files/test/TBS5530-debug.rar) (WinXP+)

**Comment by majortom9** [comment]
Thank you so much crazycat, u are awesome.
I'll have both windows users try this, and report back to you.

**Comment by majortom9** [comment]
Good News, we have a report of Windows now playing that mux perfectly with ur debug driver, like linux.
I think we can consider these bugs sqaushed now, like a fly in a venus flytrap!
Will that fix ever make it to the TBS official windows driver, or just point windows folks to yours indefinitely?

Thanks again Crazycat,

**Comment by majortom9** [comment]
For the record, windows user snagged a new TS file from the mux with the windows debug driver, and it looks good to me now.
They did mention they took a few hits in signal while recording, but it's a 16 apsk signal, so not surprising to me if marginal signal
quality. It's playing perfectly for em now though. fresh TSReader snapshot from the windows ts recording.
https://i.ibb.co/M5JZk0b2/Screenshot-at-2025-05-24-22-10-41.png

Let ya know how the other windows user makes out, when they get it all installed.

**Comment by crazycat69** [comment]
> Will that fix ever make it to the TBS official windows driver, or just point windows folks to yours indefinitely?

will be released soon

**Comment by majortom9** [comment]
Awesome thanks crazycat. Still so far so good from the windows user on the troublesome S2x mux above.

Here is another small bug I found today. Looks to me like exists in tbsdtv /latest also.

When tuning a mux of DVB-S QPSK FEC 7/8, is indicating FEC NONE.
Because it's falling through to default in m88rs6060_get_frontend().
In that function FEC 7_8 isn't listed.
This fixed it for me in linux, on my rpi. I haven't committed it to my local tree yet, but is definitely working now.
This was just an indication type issue, and wasn't affecting the performance, as ya could still
play the programs fine. Just we should definitely be able to indicate the correct FEC.
A windows user tells me they have the same issue when tuning the same DVB-S QPSK FEC 7/8  
muxes I was tuning. So may wanna review that on the windows side as well.


```
diff --git a/drivers/media/dvb-frontends/m88rs6060.c b/drivers/media/dvb-frontends/m88rs6060.c
index 49b457982e64..30cf5aaadf86 100644
--- a/drivers/media/dvb-frontends/m88rs6060.c
+++ b/drivers/media/dvb-frontends/m88rs6060.c
@@ -2449,6 +2449,7 @@ static int m88rs6060_get_frontend(struct dvb_frontend *fe, struct dtv_frontend_p
                        case MtFeCodeRate_3_4:          p->fec_inner = FEC_3_4; break;
                        case MtFeCodeRate_4_5:          p->fec_inner = FEC_4_5; break;
                        case MtFeCodeRate_5_6:          p->fec_inner = FEC_5_6; break;
+                       case MtFeCodeRate_7_8:          p->fec_inner = FEC_7_8; break;
                        case MtFeCodeRate_8_9:          p->fec_inner = FEC_8_9; break;
                        case MtFeCodeRate_9_10: p->fec_inner = FEC_9_10;        break;
                        case MtFeCodeRate_5_9:          p->fec_inner = FEC_5_9; break;
```

Here's a snapper from my rpi, after fixing this one.
https://i.ibb.co/PsLNzKZ3/Screenshot-at-2025-05-25-18-14-05.png

**Comment by crazycat69** [comment]
https://github.com/tbsdtv/linux_media/commit/b00b2678fc0a23cf4956f33a84d50bde1d549fea

**Comment by majortom9** [comment]
What's your opinion about tossin a crude m88rs6060_search() in there?
I've been playin around in linux for the last week, and came up with a way to try DVB-S2(x) first, then try DVB-S if no lock.
As long as the SR is "guessed" at about 20% higher than the actual SR, S2 will lock in about 1/2 sec, and 
DVB-2 in about a second, and returns the actual SR.

**Comment by majortom9** [comment]
Looks like fix for windows tbs5930 was published, but I didn't see an update to the tbs5530 like you had done for the debug...
I don't know anyone this side of the pond that would have a tbs5530, obviously.
Windows user confirms the official tbs5930 is working for the Win10 driver now though.
